stages:
  - sync-code
  - build
  - deploy

sync-code:
  stage: sync-code
  only:
    - master
  script:
    - export GIT_NAME_DIR=`grep -E "url = .*.git" $PWD/.git/config|awk -F 'qiushaocloud/' '{print $2}' | sed s/\.git//g`
    - git config --global user.email "qiushaocloud@126.com"
    - git config --global user.name "qiushaocloud"
    - export GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no"
    - mkdir -p /root/codes && cd /root/codes
    #- chmod 600 /root/.ssh/id_rsa
    - git clone ssh://git@gitlab.qiushaocloud.top:61023/qiushaocloud/$GIT_NAME_DIR.git
    - cd $GIT_NAME_DIR && echo `pwd`
    - sh push-remote-git-repos.sh
  tags:
    - qiushaocloud-runner

build:
  stage: build
  only:
    - master
  script:
    - docker build -t qiushaocloud/redis-web-manager:latest .
  tags:
    - qiushaocloud-runner

deploy:
  stage: deploy
  only:
    - master
  script:
    - docker login --username $DOCKER_HUB_USER_NAME --password $DOCKER_HUB_USER_PASSWORD
    - docker push qiushaocloud/redis-web-manager:latest
  tags:
    - qiushaocloud-runner

build-tags:
  stage: build
  only:
    - tags
  script:
    - docker build -t qiushaocloud/redis-web-manager:latest .
    - docker tag qiushaocloud/redis-web-manager:latest qiushaocloud/redis-web-manager:$CI_COMMIT_REF_NAME
  tags:
    - qiushaocloud-runner

deploy-tags:
  stage: deploy
  only:
    - tags
  script:
    - docker login --username $DOCKER_HUB_USER_NAME --password $DOCKER_HUB_USER_PASSWORD
    - docker push qiushaocloud/redis-web-manager:latest
    - docker push qiushaocloud/redis-web-manager:$CI_COMMIT_REF_NAME
  tags:
    - qiushaocloud-runner
