version:  '3'
services:
  qiushao-redis-web-manager:
      image: qiushaocloud/redis-web-manager
      container_name: qiushao-redis-web-manager
      hostname: qiushao-redis-web-manager
      network_mode: $NETWORK_MODE
      ports:
        - $EXTERNAL_SVC_PORT:$SERVER_PORT
      volumes:
        - $RDM_DATA_DIR:/data
        - $MYSQL_DIR/var_lib_mysql:/var/lib/mysql
      env_file: .env